<?php

return [
	'rules folder' => '/rules/',
	'rules extension' => 'php',
	'filters folder' => '/filters/',
	'filters extension' => 'php',
	'rules' => [
		'is_unique' => '\\projectorangebox\\validate\\rules\\Is_unique',
		'has_errors' => '\\projectorangebox\\validate\\rules\\Has_errors',
		'decimal' => '\\projectorangebox\\validate\\rules\\Decimal',
		'matches' => '\\projectorangebox\\validate\\rules\\Matches',
		'alpha_numeric' => '\\projectorangebox\\validate\\rules\\Alpha_numeric',
		'greater_than' => '\\projectorangebox\\validate\\rules\\Greater_than',
		'alpha_space' => '\\projectorangebox\\validate\\rules\\Alpha_space',
		'greater_than_equal_to' => '\\projectorangebox\\validate\\rules\\Greater_than_equal_to',
		'is_natural_no_zero' => '\\projectorangebox\\validate\\rules\\Is_natural_no_zero',
		'alpha_dash' => '\\projectorangebox\\validate\\rules\\Alpha_dash',
		'regex_match' => '\\projectorangebox\\validate\\rules\\Regex_match',
		'alpha' => '\\projectorangebox\\validate\\rules\\Alpha',
		'alpha_numeric_spaces' => '\\projectorangebox\\validate\\rules\\Alpha_numeric_spaces',
		'valid_url' => '\\projectorangebox\\validate\\rules\\Valid_url',
		'min_length' => '\\projectorangebox\\validate\\rules\\Min_length',
		'valid_emails' => '\\projectorangebox\\validate\\rules\\Valid_emails',
		'numeric' => '\\projectorangebox\\validate\\rules\\Numeric',
		'less_than' => '\\projectorangebox\\validate\\rules\\Less_than',
		'is_uniquem' => '\\projectorangebox\\validate\\rules\\Is_uniquem',
		'required' => '\\projectorangebox\\validate\\rules\\Required',
		'is_natural' => '\\projectorangebox\\validate\\rules\\Is_natural',
		'if_empty' => '\\projectorangebox\\validate\\rules\\If_empty',
		'integer' => '\\projectorangebox\\validate\\rules\\Integer',
		'valid_email' => '\\projectorangebox\\validate\\rules\\Valid_email',
		'differs' => '\\projectorangebox\\validate\\rules\\Differs',
		'exact_length' => '\\projectorangebox\\validate\\rules\\Exact_length',
		'max_length' => '\\projectorangebox\\validate\\rules\\Max_length',
		'less_than_equal_to' => '\\projectorangebox\\validate\\rules\\Less_than_equal_to',
		'in_list' => '\\projectorangebox\\validate\\rules\\In_list',
		'valid_base64' => '\\projectorangebox\\validate\\rules\\Valid_base64',
		'valid_ip' => '\\projectorangebox\\validate\\rules\\Valid_ip',
	],
	'filters' => [
		'slug' => '\\projectorangebox\\validate\\filters\\Slug',
		'convert_date' => '\\projectorangebox\\validate\\filters\\Convert_date',
		'length' => '\\projectorangebox\\validate\\filters\\Length',
		'textarea' => '\\projectorangebox\\validate\\filters\\Textarea',
		'input' => '\\projectorangebox\\validate\\filters\\Input',
		'filename' => '\\projectorangebox\\validate\\filters\\Filename',
		'str' => '\\projectorangebox\\validate\\filters\\Str',
		'visible' => '\\projectorangebox\\validate\\filters\\Visible',
		'human' => '\\projectorangebox\\validate\\filters\\Human',
		'integer' => '\\projectorangebox\\validate\\filters\\Integer',
		'number' => '\\projectorangebox\\validate\\filters\\Number',
	],
];
